# Generated by Django 3.1.2 on 2021-04-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flower_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('bouquet_type', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
