# Generated by Django 3.1.2 on 2021-04-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_receive_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive_order',
            name='bouquet_type',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receive_order',
            name='description',
            field=models.TextField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receive_order',
            name='image',
            field=models.ImageField(default=-1.0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receive_order',
            name='price',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receive_order',
            name='product_name',
            field=models.CharField(default=-1.0, max_length=50),
            preserve_default=False,
        ),
    ]
